version: 1.0
provider:
  name: openfaas
  gateway: http://100.108.186.115:8080
functions:
  tri:
    lang: python3-http-debian
    handler: ./tri
    image: etudepratique/tri:latest
    environment:
      write_timeout: 120s
      read_timeout: 120s
      exec_timeout: 120s
    annotations:
      topic: "tri"
    secrets:
      - ssh-private-key

  bdd:
    lang: python3-http-debian
    handler: ./bdd
    image: etudepratique/bdd:latest
    environment:
      write_timeout: 120s
      read_timeout: 120s
      exec_timeout: 120s
    annotations:
      topic: "bdd"
    secrets:
      - ssh-private-key

